# Generated by Django 5.0.7 on 2024-07-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('UUID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Teamviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('UniqueID', models.CharField(blank=True, max_length=255, null=True)),
                ('IP', models.CharField(blank=True, max_length=255, null=True)),
                ('CabinetLink', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('AnyDesk', models.CharField(blank=True, max_length=255, null=True)),
                ('DeviceName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('UUID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('GK', models.CharField(blank=True, max_length=255, null=True)),
                ('Teamviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('AnyDesk', models.CharField(blank=True, max_length=255, null=True)),
                ('DeviceName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastModifiedDate', models.DateTimeField(blank=True, null=True)),
                ('ownerTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('ownerUUID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
