# Generated by Django 5.0.7 on 2024-07-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ownerUUID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
