# Generated by Django 5.0.7 on 2024-07-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_server_owneruuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ownerTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
