# Generated by Django 5.0.7 on 2024-07-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_server_ownertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cleared_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
